### PR TITLE
Update got to v12, file-ext to v18 & split got/decompress options

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by danez** [comment]
What is your opinion about ditching got all together and using node-fetch instead?
The reason I'm asking is because node 18 introduced it natively it might make sense to reevaluate if we actually really need `the power of got` :) or if fetch would be sufficient and we wouldn't even need an external dependency in the future.

Afaics streaming should work with fetch, but I can try this out. IF you are not against it I would be happy to create a PR.

**Comment by XhmikosR** [comment]
https://packagephobia.com/result?p=got%2Cnode-fetch

So, it looks like got is smaller than node-fetch.

It will probably make more sense when we drop Node.js 16 support.

How do the changes look to you so far?

BTW if you want push rights, let me know, I could use any help since I mostly began forking and updating these packages for bin-wrapper and netlify :)

**Review by danez — APPROVED** [review]
Looks good. I like the clear distinction between the options. Unfortunately this will take some time, until this will be updated in netlify, because we are not yet at the point of dropping node 14. but once we do it is good to know that this will be ready :)

**Comment by XhmikosR** [comment]
I could probably keep Node.js 14 support, shouldn't be too hard. I'll give it a go.

Actually, `defaults` doesn't seem to support Node.js 14. Do you have any other small package suggestions?

filenamify 5.x works on Node.js 14, so only `defaults` is the issue.

**Comment by XhmikosR** [comment]
Actually, `defaults` doesn't seem to support Node.js 14. Do you have any other small package suggestions?

filenamify 6.0.0 works on Node.js 14, so only `defaults` is the issue.

**Comment by XhmikosR** [comment]
I went with `merge-options`, let me know what you think @danez!

**Pull request merged**
